name: ad_hoc_ident_ocr_extract_google
description: "Provides OCR functionality as part of the ad_hoc_ident framework."
version: 0.0.1-preview-1
homepage: https://github.com/FabianMoeckel/ad_hoc_ident_ocr_extract_google
repository: https://github.com/FabianMoeckel/ad_hoc_ident_ocr_extract_google


environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.13.0
  ad_hoc_ident_ocr: ^0.0.1-preview-1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
